# .github/workflows/auto-merge-txt.yml

name: Auto Merge Request Files

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    if: github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 2

      - name: Fetch base branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}

      - name: Check changed files only in requests folder
        id: check
        run: |
          changed_files=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} HEAD)
          echo "$changed_files"

          only_requests=true
          for file in $changed_files; do
            if [[ "$file" != requests/*.txt ]]; then
              only_requests=false
              break
            fi
          done

          echo "only_requests=$only_requests" >> $GITHUB_OUTPUT

      - name: Enable auto-merge
        if: steps.check.outputs.only_requests == 'true'
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Skip auto-merge (invalid changes)
        if: steps.check.outputs.only_requests != 'true'
        run: |
          echo "PR contains files outside the 'requests' folder. Auto-merge skipped."
